# main menu
[[main]]
name = "ホーム"
url = "/"
weight = 1
hasChildren = true

[[main]]
parent = "ホーム"
name = "ゲームについて"
url = "about-game/"
weight = 1

[[main]]
parent = "ホーム"
name = "目指すこと"
url = "mission/"
weight = 2

[[main]]
parent = "ホーム"
name = "お知らせ"
url = "news/"
weight = 3



[[main]]
name = "学べること"
url = "learn/"
weight = 2




[[main]]
name = "遊び方"
weight = 3
hasChildren = true

[[main]]
parent = "遊び方"
name = "アイスブレイクルール"
url = "icebreak-rules/"
weight = 1

[[main]]
parent = "遊び方"
name = "まちづくりルール"
url = "city-building-rules/"
weight = 2

[[main]]
parent = "遊び方"
name = "ビジネスルール"
url = "business-rules/"
weight = 3



[[main]]
weight = 4
name = "その他"
hasChildren = true

[[main]]
parent = "その他"
name = "利用事例"
url = "blog/"
weight = 1

[[main]]
parent = "その他"
name = "よくあるご質問"
url = "faq/"
weight = 2

[[main]]
parent = "その他"
name = "ご購入"
url = "purchase/"
weight = 3

[[main]]
parent = "その他"
name = "印刷データ"
url = "print-data/"
weight = 4

[[main]]
parent = "その他"
name = "開発ラボ"
url = "development-lab/"
weight = 5

[[main]]
parent = "その他"
name = "作った人"
url = "creator/"
weight = 6




# footer menu
[[footer]]
name = "トップ"
url = "/"
weight = 1

[[footer]]
name = "制作者について"
url = "creator/"
weight = 2

[[footer]]
name = "プライバシーポリシー"
url = "privacy-policy/"
weight = 3
